# Generated by Django 2.1.2 on 2018-11-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0003_auto_20181106_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='addedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
